In [1]:
!pip3 install torch

In [2]:
import torch

In [3]:
v=torch.tensor([1,2,3,4,5,6])
f=torch.FloatTensor([1.1,2.2,3])
f1=torch.tensor([1.1,2.2,3])
print(v)
print(v[2])
print(v[1:2])
print(f)
print(f1)
print(f[2])
print(f[1:2])
print(f.dtype)
print(f1.dtype)
print(f.size())

tensor([1, 2, 3, 4, 5, 6])
tensor(3)
tensor([2])
tensor([1.1000, 2.2000, 3.0000])
tensor([1.1000, 2.2000, 3.0000])
tensor(3.)
tensor([2.2000])
torch.float32
torch.float32
torch.Size([3])


In [4]:
v.view(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [5]:
v.view(2,-1)


tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
t1= torch.tensor([1,2,3,4])
t2=torch.tensor([1,2,3,4])

print(t1+t2)
print(t1-t2)
print(t1*t2)
print(t1/t2)
print(t1**t2)
print(t1%t2)

tensor([2, 4, 6, 8])
tensor([0, 0, 0, 0])
tensor([ 1,  4,  9, 16])
tensor([1., 1., 1., 1.])
tensor([  1,   4,  27, 256])
tensor([0, 0, 0, 0])


In [7]:
A = torch.tensor([1, 2, 3])
B = torch.tensor([4, 5, 6])

dot_product = torch.dot(A, B)
print(dot_product)  # Output: tensor(32)
#For higher-dimensional tensors, you use torch.matmul or the @ operator
# for matrix multiplication, which is a generalization of the dot product:
C = torch.tensor([[1, 2], [3, 4]])
D = torch.tensor([[5, 6], [7, 8]])

matrix_product = torch.matmul(C, D)
print(matrix_product)

tensor(32)
tensor([[19, 22],
        [43, 50]])


In [8]:
x=torch.arange(18).view(3,2,3)
print(x[0,1, 2])
print(x[0:1,:,:])
# x

tensor(5)
tensor([[[0, 1, 2],
         [3, 4, 5]]])


In [9]:
mat_a = torch.tensor([0, 3, 5, 5, 5, 2]).view(2, 3)
print(mat_a)
mat_b = torch.tensor([3, 4, 3, -2, 4, -2]).view(3, 2)
print(mat_b)
print(torch.matmul(mat_a, mat_b))
print(mat_a@mat_b)

tensor([[0, 3, 5],
        [5, 5, 2]])
tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])
tensor([[ 29, -16],
        [ 38,   6]])
tensor([[ 29, -16],
        [ 38,   6]])
